export const keyMap = {
  Alt: "⎇",
  AltGraph: "⎈",
  CapsLock: "⇪",
  Control: "⌃",
  Meta: { mac: "⌘", win: "⊞", lin: "◆" },
  OS: { mac: "⌘", win: "⊞", lin: "◆" },
  NumLock: "⇭",
  ScrollLock: "⇳",
  Shift: "⇧",
  Pause: "⏸",
  PrintScreen: "⎙",
  ContextMenu: "▤",
  Enter: "⏎",
  Escape: "⎋",
  Backspace: "⌫",
  Tab: "⇥",
  Space: "␣",
  Delete: "⌦",
  Insert: "⎀",
  Home: "⇱",
  End: "⇲",
  PageUp: "⇞",
  PageDown: "⇟",
  ArrowUp: "↑",
  ArrowDown: "↓",
  ArrowLeft: "←",
  ArrowRight: "→",
};
